---
###############################################################################
# nexus-docker.yml
#     create the Nexus3 docker container
#
###############################################################################

# Create the Nexus3 containter 
# docker run -d -p 8081:8081 --name nexus sonatype/nexus3
- name: Create Nexus container
  community.general.docker_container:
     name: nexus3
     image: sonatype/nexus3:latest
     container_default_behavior: compatibility
     state: started
     privileged: yes
     network_mode: host
     restart: yes
     restart_policy: always

- name: Run a command to get password in Nexus3
  ansible.builtin.shell: docker container exec nexus3 cat nexus-data/admin.password
